name: Exploring Variables and Secrets
on:
  push:
    branches:
      - main
env:
  SOURCE_IMAGE: leonardorothier/email-site
  TARGET_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: leonardorothier
      SOURCE_TAG: v5

    steps:
      - name: Docker Pull
        run: docker pull $SOURCE_IMAGE:$SOURCE_TAG

      - name: Tag with 'latest'
        run: docker tag $SOURCE_IMAGE:$SOURCE_TAG $SOURCE_IMAGE:$TARGET_TAG

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Push to Docker Hub
        run: docker push $SOURCE_IMAGE:$TARGET_TAG
  deploy:
    needs: build
    runs-on: ubuntu-latest
    concurrency:
      group: production-deployment
      cancel-in-progress: false
    steps:
      - name: Run Test Container
        run: docker run -d -p 8080:8080 --name=email-site $SOURCE_IMAGE:$TARGET_TAG

      
